"""Alembic: the chain runs forwards, backwards and forwards again, and it carries
an existing archive across (docs/ROADMAP.md M2, R#23, R#14).

Every test here works on its own throwaway database next to the one the API tests
use, so it can drop and rebuild a schema without disturbing anything.
"""

import os
import uuid
from contextlib import contextmanager

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.engine import make_url

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def alembic_config(url: str) -> Config:
    config = Config(os.path.join(REPO_ROOT, "alembic.ini"))
    config.set_main_option("script_location", os.path.join(REPO_ROOT, "alembic"))
    config.set_main_option("sqlalchemy.url", url)
    return config


def run(url: str, action, target: str) -> None:
    engine = create_engine(url)
    try:
        with engine.begin() as connection:
            config = alembic_config(url)
            config.attributes["connection"] = connection
            action(config, target)
    finally:
        engine.dispose()


@contextmanager
def scratch_database():
    """A fresh, empty database, dropped again afterwards."""
    base = make_url(os.environ["DATABASE_URL"])
    name = f"negarchive_mig_{uuid.uuid4().hex[:8]}"
    admin = create_engine(base.set(database="postgres"), isolation_level="AUTOCOMMIT")
    try:
        with admin.connect() as connection:
            connection.execute(text(f'CREATE DATABASE "{name}"'))
    except Exception as exc:  # pragma: no cover - depends on the server's grants
        admin.dispose()
        pytest.skip(f"cannot create a scratch database: {exc}")
    try:
        # str(URL) masks the password; the migration runner needs the real one.
        yield base.set(database=name).render_as_string(hide_password=False)
    finally:
        with admin.connect() as connection:
            connection.execute(
                text(
                    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                    "WHERE datname = :name AND pid <> pg_backend_pid()"
                ),
                {"name": name},
            )
            connection.execute(text(f'DROP DATABASE IF EXISTS "{name}"'))
        admin.dispose()


def tables(url: str) -> set:
    engine = create_engine(url)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def columns(url: str, table: str) -> dict:
    engine = create_engine(url)
    try:
        return {c["name"]: c for c in inspect(engine).get_columns(table)}
    finally:
        engine.dispose()


def test_upgrade_downgrade_upgrade_on_an_empty_database():
    with scratch_database() as url:
        run(url, command.upgrade, "head")
        after_upgrade = tables(url)
        assert {"film_rolls", "image_assets", "cameras", "lenses", "film_stocks"} <= after_upgrade
        # R#10/R#15: face detection is gone, tables and all
        assert "faces" not in after_upgrade and "persons" not in after_upgrade

        run(url, command.downgrade, "base")
        assert tables(url) - {"alembic_version"} == set()

        # The enum types must have gone with the tables, or this fails.
        run(url, command.upgrade, "head")
        assert tables(url) == after_upgrade


def test_head_matches_the_models():
    """`alembic check`: the models and the migration chain agree."""
    with scratch_database() as url:
        run(url, command.upgrade, "head")
        engine = create_engine(url)
        try:
            with engine.begin() as connection:
                config = alembic_config(url)
                config.attributes["connection"] = connection
                command.check(config)  # raises AutogenerateDiffsDetected on drift
        finally:
            engine.dispose()


def test_the_m2_columns_are_there():
    with scratch_database() as url:
        run(url, command.upgrade, "head")

        images = columns(url, "image_assets")
        assert "original_filename" in images
        # M3 relies on this default: an image is 'managed' unless it says otherwise.
        assert images["storage_mode"]["nullable"] is False
        assert "managed" in str(images["storage_mode"]["default"])

        rolls = columns(url, "film_rolls")
        for column in ("camera_id", "lens_id", "film_stock_id", "format"):
            assert column in rolls
        # The name columns stay for one release.
        for column in ("camera", "lens", "film_type"):
            assert column in rolls

        stocks = columns(url, "film_stocks")
        assert "manufacturer" in stocks and "format" in stocks


def test_gear_foreign_keys_set_null_on_delete():
    with scratch_database() as url:
        run(url, command.upgrade, "head")
        engine = create_engine(url)
        try:
            constraints = inspect(engine).get_foreign_keys("film_rolls")
            by_column = {fk["constrained_columns"][0]: fk for fk in constraints}
            for column in ("camera_id", "lens_id", "film_stock_id"):
                assert by_column[column]["options"].get("ondelete") == "SET NULL", column

            # and it really behaves that way
            with engine.begin() as connection:
                connection.execute(
                    text("INSERT INTO cameras (id, name, created_at) VALUES (1, 'F5', now())")
                )
                connection.execute(
                    text(
                        "INSERT INTO film_rolls (title, camera_id, camera, created_at) "
                        "VALUES ('Roll', 1, 'F5', now())"
                    )
                )
                connection.execute(text("DELETE FROM cameras WHERE id = 1"))
                row = connection.execute(
                    text("SELECT camera_id, camera FROM film_rolls")
                ).one()
            assert row.camera_id is None
            assert row.camera == "F5", "the name survives so the roll still says what shot it"
        finally:
            engine.dispose()


def test_an_existing_pre_m2_archive_is_carried_across():
    """The upgrade path for somebody who has been running NegArchive since M0.

    ``0001_baseline`` *is* the pre-M2 schema, so stopping there and filling it with
    rolls, gear and images reproduces a real installation; ``upgrade head`` then has
    to preserve the data and backfill the new foreign keys (R#14).
    """
    with scratch_database() as url:
        run(url, command.upgrade, "0001_baseline")
        assert {"faces", "persons"} <= tables(url)

        engine = create_engine(url)
        try:
            with engine.begin() as connection:
                connection.execute(
                    text("INSERT INTO cameras (id, name, created_at) VALUES (7, 'Nikon F5', now())")
                )
                connection.execute(
                    text("INSERT INTO lenses (id, name, created_at) VALUES (3, 'Nikkor 50mm', now())")
                )
                connection.execute(
                    text(
                        "INSERT INTO film_stocks (id, name, kind, created_at) "
                        "VALUES (5, 'Fomapan 400', 'black_and_white', now())"
                    )
                )
                connection.execute(
                    text(
                        "INSERT INTO film_rolls (id, title, camera, lens, film_type, created_at) "
                        "VALUES (1, 'Japan 2024', ' nikon f5 ', 'Nikkor 50mm', 'Fomapan 400', now())"
                    )
                )
                connection.execute(
                    text(
                        "INSERT INTO film_rolls (id, title, camera, created_at) "
                        "VALUES (2, 'Unknown gear', 'Some Other Camera', now())"
                    )
                )
                connection.execute(
                    text(
                        "INSERT INTO image_assets (film_roll_id, type, path, frame_number, created_at) "
                        "VALUES (1, 'scan', 'static/uploads/scans/abc.tif', 7, now())"
                    )
                )

            run(url, command.upgrade, "head")

            with engine.begin() as connection:
                rolls = connection.execute(
                    text("SELECT id, title, camera_id, lens_id, film_stock_id, camera FROM film_rolls ORDER BY id")
                ).all()
                images = connection.execute(
                    text(
                        "SELECT path, frame_number, original_filename, storage_mode FROM image_assets"
                    )
                ).all()
        finally:
            engine.dispose()

        first, second = rolls
        # Backfilled by name, case- and whitespace-insensitively.
        assert (first.camera_id, first.lens_id, first.film_stock_id) == (7, 3, 5)
        assert first.title == "Japan 2024"
        # A name with no catalog entry keeps its free text and gets no id.
        assert second.camera_id is None and second.camera == "Some Other Camera"

        assert len(images) == 1
        assert images[0].path == "static/uploads/scans/abc.tif"
        assert images[0].frame_number == 7
        assert images[0].original_filename is None, "nothing to invent for old rows"
        assert images[0].storage_mode == "managed"

        assert "faces" not in tables(url) and "persons" not in tables(url)


def test_the_baseline_is_a_no_op_on_a_schema_that_already_exists():
    """A pre-Alembic database must not be rebuilt, only stamped."""
    with scratch_database() as url:
        run(url, command.upgrade, "0001_baseline")
        engine = create_engine(url)
        try:
            with engine.begin() as connection:
                connection.execute(
                    text("INSERT INTO film_rolls (id, title, created_at) VALUES (99, 'Keep me', now())")
                )
                connection.execute(text("DELETE FROM alembic_version"))
            # Now it looks exactly like a database that predates Alembic.
            run(url, command.upgrade, "head")
            with engine.begin() as connection:
                kept = connection.execute(
                    text("SELECT title FROM film_rolls WHERE id = 99")
                ).scalar()
                stamped = connection.execute(text("SELECT version_num FROM alembic_version")).scalar()
        finally:
            engine.dispose()
        assert kept == "Keep me"
        assert stamped == "0002_m2_archive_integrity"
